### ISSUE TITLE
Can't have two apps running Gnonative at the same time

### ISSUE THREAD

**Issue by iuricmp** [gnolang/gnonative#142]
How to reproduce:

- Install two apps that use '@gnolang/gnonative' same device.
- Open the first app.
- Open the second app.

The second app will throw an error saying the TCP port is already in use.

<img width="293" alt="Screenshot 2024-05-17 at 11 30 15" src="https://github.com/gnolang/gnonative/assets/689440/e12f6b34-d144-48e2-b3d7-4bc378f2ce4b">

We need to implement a way to dynamically choose a new free port.

**Comment by jefft0** [comment]
NOTE: This may be a problem if the mobile is running both dSocial and Gnokey Mobile.
