### ISSUE TITLE
Setting Up Apple Developer Account for App Store Submission

### ISSUE THREAD

**Issue by iuricmp** [gnolang/gnonative#41]
Our team is preparing to submit the Gnomobile to _Testflight_ and the _App Store_, but we don't have an Apple Developer account yet. 

We need to decide who will be responsible for creating the Apple Developer account needed for our app's submission to _Testflight_ and _App Store_. We also need to include Gnomobile team members as administrators to ensure we have the necessary access and privileges.

**Comment by moul** [comment]
👍  I will manage it, thank you.

**Comment by jefft0** [comment]
@iuricmp pinged moul for status.

**Comment by jefft0** [comment]
Revisit after the new company is set up.

**Comment by jefft0** [comment]
"Unlock in two weeks with an invite code."

**Comment by iuricmp** [comment]
The Apple Account for this project was created under Berty's Account.
