### ISSUE TITLE
Setting Up Google Developer Account for Play Store Submission

### ISSUE THREAD

**Issue by iuricmp** [gnolang/gnonative#42]
Our team is preparing to submit the Gnomobile to the Google Play Store but we don't have a Google Developer account yet.

We need to decide who will be responsible for creating the Google Developer account needed for our app's submission to the Google Play Store. We also need to include Gnomobile team members as administrators to ensure we have the necessary access and privileges.

**Comment by moul** [comment]
I will manage it.

**Comment by jefft0** [comment]
@iuricmp pinged moul for status.

**Comment by jefft0** [comment]
Revisit after the new company is set up.

**Comment by jefft0** [comment]
"Unlock in two weeks with an invite code."

**Comment by iuricmp** [comment]
The Android App Store Account for this project was created under Berty's Account.
